global:
  scrape_interval:     10s
  evaluation_interval: 60s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: prometheus

  - job_name: local_host
    metrics_path: /metrics/host
    scheme: http
    static_configs:
      - targets: ['10.10.32.96:9100']
        labels:
          instance: localhost




  - job_name: local_docker
    metrics_path: /metrics/docker
    scheme: http
    static_configs:
      - targets: ['10.10.32.96:9100']
        labels:
          instance: localhost
